# Generated by Django 3.0.2 on 2020-03-10 23:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courtinfractions', '0013_auto_20200310_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='sportOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='memberRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(max_length=3)),
                ('joinDate', models.DateField(default=django.utils.timezone.now)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courtinfractions.contactInfo')),
                ('sportPrefs', models.ManyToManyField(to='memberexperience.sportOptions')),
            ],
        ),
    ]
