# Generated by Django 3.1 on 2020-09-02 02:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courtinfractions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='sportOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='memberRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('joinDate', models.DateField(default=django.utils.timezone.now)),
                ('followUp1', models.DateField(default=datetime.datetime(2020, 12, 2, 2, 47, 32, 819686, tzinfo=utc))),
                ('followUp2', models.DateField(default=datetime.datetime(2021, 3, 3, 2, 47, 32, 819710, tzinfo=utc))),
                ('followUp3', models.DateField(default=datetime.datetime(2021, 9, 2, 2, 47, 32, 819721, tzinfo=utc))),
                ('notes', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courtinfractions.contactinfo')),
                ('sportPrefs', models.ManyToManyField(to='memberexperience.sportOptions')),
            ],
        ),
    ]
