# Generated by Django 3.1 on 2020-09-02 02:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('memberexperience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrecord',
            name='followUp1',
            field=models.DateField(default=datetime.datetime(2020, 12, 2, 2, 47, 52, 917080, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='memberrecord',
            name='followUp2',
            field=models.DateField(default=datetime.datetime(2021, 3, 3, 2, 47, 52, 917104, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='memberrecord',
            name='followUp3',
            field=models.DateField(default=datetime.datetime(2021, 9, 2, 2, 47, 52, 917116, tzinfo=utc)),
        ),
    ]
