# Generated by Django 3.0.2 on 2020-03-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberexperience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrecord',
            name='age',
            field=models.IntegerField(),
        ),
    ]
