# Generated by Django 3.0.2 on 2020-03-11 17:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('memberexperience', '0002_auto_20200310_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrecord',
            name='Notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memberrecord',
            name='followUp1',
            field=models.DateField(default=datetime.datetime(2020, 6, 10, 17, 2, 8, 4360, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='memberrecord',
            name='followUp2',
            field=models.DateField(default=datetime.datetime(2020, 9, 9, 17, 2, 8, 4382, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='memberrecord',
            name='followUp3',
            field=models.DateField(default=datetime.datetime(2021, 3, 11, 17, 2, 8, 4393, tzinfo=utc)),
        ),
    ]
