# Generated by Django 3.0.2 on 2020-03-12 22:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('memberexperience', '0004_auto_20200311_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrecord',
            name='followUp1',
            field=models.DateField(default=datetime.datetime(2020, 6, 11, 22, 10, 46, 149592, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='memberrecord',
            name='followUp2',
            field=models.DateField(default=datetime.datetime(2020, 9, 10, 22, 10, 46, 149616, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='memberrecord',
            name='followUp3',
            field=models.DateField(default=datetime.datetime(2021, 3, 12, 22, 10, 46, 149629, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='memberrecord',
            name='sportPrefs',
        ),
        migrations.AddField(
            model_name='memberrecord',
            name='sportPrefs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='memberexperience.sportOptions'),
            preserve_default=False,
        ),
    ]
