# Generated by Django 3.0.2 on 2020-03-12 22:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('memberexperience', '0005_auto_20200312_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrecord',
            name='followUp1',
            field=models.DateField(default=datetime.datetime(2020, 6, 11, 22, 52, 50, 266495, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='memberrecord',
            name='followUp2',
            field=models.DateField(default=datetime.datetime(2020, 9, 10, 22, 52, 50, 266520, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='memberrecord',
            name='followUp3',
            field=models.DateField(default=datetime.datetime(2021, 3, 12, 22, 52, 50, 266532, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='memberrecord',
            name='sportPrefs',
        ),
        migrations.AddField(
            model_name='memberrecord',
            name='sportPrefs',
            field=models.ManyToManyField(to='memberexperience.sportOptions'),
        ),
    ]
