# Generated by Django 3.0.2 on 2020-07-17 22:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('memberexperience', '0007_auto_20200314_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrecord',
            name='followUp1',
            field=models.DateField(default=datetime.datetime(2020, 10, 16, 22, 45, 22, 66063, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='memberrecord',
            name='followUp2',
            field=models.DateField(default=datetime.datetime(2021, 1, 15, 22, 45, 22, 66090, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='memberrecord',
            name='followUp3',
            field=models.DateField(default=datetime.datetime(2021, 7, 17, 22, 45, 22, 66103, tzinfo=utc)),
        ),
    ]
