# Generated by Django 3.0.2 on 2020-02-20 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courtinfractions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courtinf',
            old_name='date',
            new_name='date_posted',
        ),
    ]
