# Generated by Django 3.1 on 2020-09-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtinfractions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtinf',
            name='sport',
            field=models.CharField(choices=[('TN', 'Tennis'), ('SQ', 'Squash'), ('BM', 'Badminton'), ('PB', 'Pickleball'), ('PT', 'Platform Tennis')], max_length=2),
        ),
    ]
