# Generated by Django 3.0.2 on 2020-02-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtinfractions', '0003_auto_20200220_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtinf',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
