# Generated by Django 3.0.2 on 2020-02-26 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courtinfractions', '0004_courtinf_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtinf',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
