# Generated by Django 3.0.2 on 2020-02-28 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courtinfractions', '0006_courtinf_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courtinf',
            old_name='time',
            new_name='courtTime',
        ),
    ]
