# Generated by Django 3.0.2 on 2020-03-01 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courtinfractions', '0007_auto_20200228_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='courtinf',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courtinfractions.contactInfo'),
        ),
    ]
