# Generated by Django 3.0.2 on 2020-03-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtinfractions', '0009_auto_20200301_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtinf',
            name='sport',
            field=models.CharField(choices=[('SQ', 'Squash'), ('TN', 'Tennis')], default='Tennis', max_length=2),
        ),
        migrations.AlterField(
            model_name='courtinf',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
