# Generated by Django 3.0.2 on 2020-03-01 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courtinfractions', '0011_auto_20200301_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtinf',
            name='courtTime',
            field=models.CharField(choices=[('5:40 AM', '5:40 AM'), ('6:00 AM', '6:00 AM'), ('6:20 AM', '6:20 AM'), ('7:00 AM', '7:00 AM'), ('7:40 AM', '7:40 AM'), ('8:00 AM', '8:00 AM'), ('8:20 AM', '8:20 AM'), ('9:00 AM', '9:00 AM'), ('9:40 AM', '9:40 AM'), ('10:00 AM', '10:00 AM'), ('10:20 AM', '10:20 AM'), ('11:00 AM', '11:00 AM'), ('11:40 AM', '11:40 AM'), ('12:00 PM', '12:00 PM'), ('12:15 PM', '12:15 PM'), ('12:20 PM', '12:20 PM'), ('1:00 PM', '1:00 PM'), ('1:15 PM', '1:15 PM'), ('1:40 PM', '1:40 PM'), ('2:00 PM', '2:00 PM'), ('2:15 PM', '2:15 PM'), ('2:20 PM', '2:20 PM'), ('3:00 PM', '3:00 PM'), ('3:30 PM', '3:30 PM'), ('3:40 PM', '3:40 PM'), ('4:00 PM', '4:00 PM'), ('4:20 PM', '4:20 PM'), ('4:30 PM', '4:30 PM'), ('5:00 PM', '5:00 PM'), ('5:30 PM', '5:30 PM'), ('5:40 PM', '5:40 PM'), ('6:00 PM', '6:00 PM'), ('6:20 PM', '6:20 PM'), ('6:30 PM', '6:30 PM'), ('7:00 PM', '7:00 PM'), ('7:30 PM', '7:30 PM'), ('7:40 PM', '7:40 PM'), ('8:00 PM', '8:00 PM'), ('8:20 PM', '8:20 PM'), ('8:30 PM', '8:30 PM'), ('9:00 PM', '9:00 PM'), ('9:30 PM', '9:30 PM'), ('9:40 PM', '9:40 PM')], max_length=8),
        ),
        migrations.AlterField(
            model_name='courtinf',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='courtinf',
            name='infraction',
            field=models.CharField(choices=[('LC1', 'Late Cancel'), ('NS1', 'No Show'), ('SD1', 'Singles to Doubles'), ('GN1', 'No Show'), ('OTH', 'Other (Please specify in notes)')], max_length=3),
        ),
        migrations.AlterField(
            model_name='courtinf',
            name='sport',
            field=models.CharField(choices=[('TN', 'Tennis'), ('SQ', 'Squash')], max_length=2),
        ),
    ]
