# Generated by Django 3.0.2 on 2020-03-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtinfractions', '0012_auto_20200301_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtinf',
            name='infraction',
            field=models.CharField(choices=[('LC1', 'Late Cancel'), ('NS1', 'No Show'), ('SD1', 'Singles to Doubles'), ('GN1', 'Guest Name'), ('OTH', 'Other (Please specify in notes)')], max_length=3),
        ),
    ]
