# Generated by Django 3.0.2 on 2020-07-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtinfractions', '0013_auto_20200310_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtinf',
            name='sport',
            field=models.CharField(choices=[('TN', 'Tennis'), ('SQ', 'Squash'), ('BM', 'Badminton'), ('PB', 'Pickleball'), ('PT', 'Platform Tennis')], max_length=2),
        ),
    ]
