# Generated by Django 3.1 on 2020-09-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtinfractions', '0014_auto_20200717_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtinf',
            name='sport',
            field=models.CharField(max_length=10),
        ),
    ]
